version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - ./src:/usr/src/app/src
      - uploads:/usr/src/app/uploads
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce-platform
      PORT: 80
      SESSION_SECRET: secret
      ADMIN_EMAIL: admin@test.local
      ADMIN_PASSWORD: test1234
    command: npm run start:dev
    ports:
      - "80:80"
    networks:
      - default
    links:
      - database
      - redis
  database:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce-platform
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    links:
      - database

volumes:
  postgres:
  pgadmin:
  uploads:
